inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance
  - ./lib/rubocop/cop/text_us/dependency_injection
  - ./lib/rubocop/cop/text_us/initializer_dependencies
  - ./lib/rubocop/cop/text_us/transaction_best_practice

# In-House Cops
TextUs:
  Exclude:
    - "spec/**/*"

TextUs/DependencyInjection:
  Exclude:
    - "spec/**/*"
    - "lib/tasks/*.rake"
    - "lib/tesseract/container.rb"

Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRailsVersion: 6.0
  TargetRubyVersion: 2.7

  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "bin/**/*"
    - "script/**/*"
    - "node_modules/**/*"
    - "ui/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "work/**/*"

Layout:
  Severity: error
Lint:
  Severity: error

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/LineLength:
  Enabled: true
  Max: 140
  IgnoredPatterns:
    - '\A#  '
  Exclude:
    - db/migrate/*.rb
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"  # `expect { }.to change { }` is fine
Lint/ShadowingOuterLocalVariable:
  # Shadowing outer local variables with block parameters is often useful to
  # not reinvent a new name for the same thing, it highlights the relation
  # between the outer variable and the parameter. The cases where it's actually
  # confusing are rare, and usually bad for other reasons already, for example
  # because the method is too long.
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - db/migrate/*.rb
    - lib/tasks/**/*
    - Gemfile
    - Guardfile
    - shared_context
    - feature
    - app/admin/*
  IgnoredMethods:
    - configure
    - context
    - define
    - describe
    - factory
    - it
    - namespace
    - specify
    - task
    - shared_examples_for
    - shared_context
    - feature
    - define_type
Metrics/ClassLength:
  Exclude:
    - "spec/**/*_spec.rb"
Naming/RescuedExceptionsVariableName:
  PreferredName: ex
Naming/FileName:
  Enabled: false
Naming/AccessorMethodName:
  # Avoid writing accessors in Ruby, but this catches too many false positives
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Style/EmptyLiteral:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true
Style/HashEachMethods:
  Enabled: true
Style/HashSyntax:
  Exclude:
    - lib/tasks/**/*.rake
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/MethodCallWithoutArgsParentheses:
  Enabled: true
Style/NumericLiterals:
  Enabled: false
Style/StringChars:
  Enabled: true
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/SymbolArray:
  MinSize: 4
Style/TopLevelMethodDefinition:
  Enabled: true

# 0.81
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: false

# 0.82
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true

# 0.83
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true

# 0.84
Lint/DeprecatedOpenSSLConstant:
  Enabled: true

# 0.85
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true

# 0.86
Style/RedundantFetchBlock:
  Enabled: true
Lint/ConstantResolution:
  Enabled: false

# 0.87
Style/AccessorGrouping:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true

# 0.88
Lint/DuplicateElsifCondition:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true

# 0.89
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/EmptyConditionalBody:
  Enabled: true
Lint/FloatComparison:
  Enabled: true
Lint/MissingSuper:
  Enabled: false
Lint/OutOfRangeRegexpRef:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/TopLevelReturnWithArgument:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: true
Style/ExplicitBlockArgument:
  Enabled: true
Style/GlobalStdStream:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/SingleArgumentDig:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: true
Style/StringConcatenation:
  # `"a" + var + "b"` should be interpolated, but `"a" + var` or `var + "b"` is
  # fine concatted
  Enabled: false

# 0.90
Lint/DuplicateRequire:
  Enabled: true
Lint/EmptyFile:
  Enabled: true
Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true
Lint/UselessMethodDefinition:
  Enabled: true
Style/CombinableLoops:
  Enabled: true
Style/KeywordParametersOrder:
  Enabled: true
Style/RedundantSelfAssignment:
  Enabled: true

# 0.91
Layout/BeginEndAlignment:
  Enabled: true
Lint/ConstantDefinitionInBlock:
  Enabled: false
Lint/IdentityComparison:
  Enabled: true
Lint/UselessTimes:
  Enabled: true

# 0.93
Lint/HashCompareByIdentity:
  Enabled: true
Lint/RedundantSafeNavigation:
  Enabled: true
Style/ClassEqualityComparison:
  Enabled: true

# 1.1
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: false
Lint/ToEnumArguments:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Style/ArgumentsForwarding:
  Enabled: true
Style/SwapValues:
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  Enabled: false

#1.2
Lint/NoReturnInBeginEndBlocks:
  Enabled: false
Style/CollectionCompact:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true

# 1.3
Lint/DuplicateBranch:
  Enabled: true
Lint/EmptyClass:
  Enabled: true
Style/NilLambda:
  Enabled: true

# 1.4
Style/RedundantArgument:
  Enabled: false # Better to be explicit

# 1.5
Lint/UnexpectedBlockArity:
  Enabled: true

# 1.7
Layout/SpaceBeforeBrackets:
  Enabled: false #spaces are sometimes necessary
Lint/AmbiguousAssignment:
  Enabled: true
Style/HashExcept:
  Enabled: true

# 1.8
Lint/DeprecatedConstants:
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Style/EndlessMethod:
  Enabled: true

# 1.9

Lint/NumberedParameterAssignment:
  Enabled: true
Lint/OrAssignmentToConstant:
  Enabled: true
Lint/TripleQuotes:
  Enabled: true
Style/IfWithBooleanLiteralBranches:
  Enabled: true
Lint/SymbolConversion:
  Enabled: true

# 1.10
Gemspec/DateAssignment:
  Enabled: true
Style/HashConversion:
  Enabled: true
Performance/RedundantEqualityComparisonBlock:
  Enabled: true
Performance/RedundantSplitRegexpArgument:
  Enabled: true

# 1.18
Naming/InclusiveLanguage:
  Enabled: false
Layout/LineEndStringConcatenationIndentation:
  Enabled: true

# 1.19
Lint/AmbiguousRange:
  Enabled: true
Style/RedundantSelfAssignmentBranch:
  Enabled: true

# 1.20.0
Bundler/GemFilename:
  Description: 'Enforces the filename for managing gems.'
  Enabled: true
  VersionAdded: '<<next>>'
  EnforcedStyle: 'Gemfile'
  SupportedStyles:
    - 'Gemfile'
    - 'gems.rb'
  Include:
    - '**/Gemfile'
    - '**/gems.rb'
    - '**/Gemfile.lock'
    - '**/gems.locked'

Lint/Debugger:
  Enabled: true

# 1.21.0
Lint/AmbiguousOperatorPrecedence:
 Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler:
 Enabled: true

# 1.22.0
Lint/RequireRelativeSelfPath:
  Enabled: true
Security/IoMethods:
  Enabled: true
Style/NumberedParameters:
  Enabled: true
Style/NumberedParametersLimit:
  Enabled: true
Style/SelectByRegexp:
  Enabled: true

# 1.23.0
Gemspec/RequireMFA:
  Enabled: true
Lint/UselessRuby2Keywords:
  Enabled: true
Style/OpenStructUse:
  Enabled: false

# Rails
Rails/AddColumnIndex:
  Enabled: true
Rails/AttributeDefaultBlockValue:
  Enabled: true
Rails/CreateTableWithTimestamps:
  Enabled: false
Rails/EagerEvaluationLogMessage:
  Enabled: true
Rails/ExpandedDateRange:
  Enabled: true
Rails/FilePath:
  EnforcedStyle: slashes
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/Output:
  Enabled: true
  AutoCorrect: false
  Include:
    - '**/*.rb'
  Exclude:
    - benchmarks/**/*
    - db/seeds.rb
    - lib/tasks/**/*
    - spec/*_helper.rb
    - scripts/*
Rails/TimeZone:
  Enabled: false
Rails/I18nLocaleAssignment:
  Enabled: true
Rails/IndexBy:
  Enabled: true
Rails/IndexWith:
  Enabled: true
Rails/FindById:
  Enabled: true
Rails/ActiveRecordCallbacksOrder:
  Enabled: true
Rails/Inquiry:
  Enabled: false
Rails/MailerName:
  Enabled: true
Rails/MatchRoute:
  Enabled: true
Rails/NegateInclude:
  Enabled: true
Rails/Pluck:
  Enabled: true
Rails/PluckInWhere:
  Enabled: false
Rails/RenderInline:
  Enabled: true
Rails/RenderPlainText:
  Enabled: true
Rails/ShortI18n:
  Enabled: true
Rails/WhereEquals:
  Enabled: false
Rails/WhereExists:
  Enabled: true
Rails/AfterCommitOverride:
  Enabled: true
Rails/SkipsModelValidations:
  Exclude:
    - scripts/*
Rails/SquishedSQLHeredocs:
  Enabled: true
Rails/WhereNot:
  Enabled: true
Rails/EnvironmentVariableAccess:
  Enabled: true
Rails/UnusedIgnoredColumns:
  Enabled: true
Rails/TimeZoneAssignment:
  Enabled: true

# 2.12.0
Rails/RedundantTravelBack:
  Enabled: true

# Rspec
RSpec/Capybara/FeatureMethods:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/ExampleLength:
  Max: 10
  Exclude:
    - "spec/admin/*_spec.rb"
RSpec/ExampleWording:
  Enabled: false
RSpec/ExpectChange:
  EnforcedStyle: block
RSpec/Focus:
  Severity: error
  AutoCorrect: false
RSpec/ImplicitExpect:
  Enabled: false
RSpec/LeadingSubject:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 4
  Exclude:
    - "spec/admin/*_spec.rb"
RSpec/NestedGroups:
  Max: 4
RSpec/NotToNot:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/IdenticalEqualityAssertion:
  Enabled: true
RSpec/Rails/AvoidSetupHook:
  Enabled: true

# 1.44
RSpec/StubbedMock:
  Enabled: true

# 2.5.0
RSpec/SubjectDeclaration:
  Enabled: true
RSpec/ExcessiveDocstringSpacing:
  Enabled: true

##
# Performance
##

Performance/ChainArrayAllocation:
  # Probably a good idea, but not a fan of mutating arrays be default
  Enabled: false
Performance/OpenStruct:
  # OpenStructs are nice in specs
  Exclude:
    - "spec/**/*"

# 1.7
Performance/AncestorsInclude:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/ReverseFirst:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringInclude:
  Enabled: true

# 1.8
Performance/Sum:
  Enabled: true
Performance/CollectionLiteralInLoop:
  Enabled: true
Performance/ArraySemiInfiniteRangeSlice:
  Enabled: true

# 1.9
Performance/BlockGivenWithExplicitBlock:
  Enabled: true
Performance/ConstantRegexp:
  Enabled: true
Performance/MethodObjectAsBlock:
  Enabled: true

# 1.11
Performance/MapCompact:
  Enabled: true

# 1.12
Performance/ConcurrentMonotonicTime:
  Enabled: true

# 1.16
Lint/EmptyInPattern:
  Enabled: true
Style/InPatternThen:
  Enabled: true
Style/MultilineInPatternThen:
  Enabled: true
Style/QuotedSymbols:
  Enabled: true
